"use strict";
const{finite,fmt,clamp,lerp,allEqual,numeric}=require("./utils");
function orderStates(m){const by=new Map(m.states.map(s=>[s.id,s]));const ex=Array.isArray(m.stateOrder)?m.stateOrder.map(id=>by.get(id)).filter(Boolean):[];if(ex.length===m.states.length)return ex;const out=new Map();for(const t of m.transitions||[])if(!out.has(t.from))out.set(t.from,t.to);const r=[],seen=new Set();let id=m.startNodeId||m.states[0].id;while(id&&by.has(id)&&!seen.has(id)){seen.add(id);r.push(by.get(id));id=out.get(id)}for(const s of m.states)if(!seen.has(s.id))r.push(s);return r}
function buildSchedule(states,transitions,cfg){const map=new Map((transitions||[]).map(t=>[`${t.from}>${t.to}`,t]));const seg=[];let c=0;for(let i=0;i<states.length;i++){if(!cfg.loop&&i===states.length-1)break;const a=states[i],b=states[(i+1)%states.length],raw=map.get(`${a.id}>${b.id}`)||{},tr=raw.transition||{},tg=raw.trigger||{};const hold=tg.type==="AFTER_TIMEOUT"&&Number.isFinite(Number(tg.timeout))?Number(tg.timeout):cfg.defaultHold;const d=Number.isFinite(Number(tr.duration))?Number(tr.duration):cfg.defaultDuration;seg.push({from:a.id,to:b.id,transitionStart:c+Math.max(0,hold),transitionEnd:c+Math.max(0,hold)+Math.max(.001,d),duration:Math.max(.001,d),easing:tr.easing||{type:"EASE_OUT"}});c=seg[seg.length-1].transitionEnd}return{segments:seg,totalDuration:Math.max(c,.001),stateIds:states.map(s=>s.id)}}
function easingSpline(e){const t=e&&e.type||"EASE_OUT";if(t==="CUSTOM_CUBIC_BEZIER"&&e.easingFunctionCubicBezier){const p=e.easingFunctionCubicBezier;return`${fmt(p.x1)} ${fmt(p.y1)} ${fmt(p.x2)} ${fmt(p.y2)}`}return{LINEAR:"0 0 1 1",EASE_IN:".42 0 1 1",EASE_OUT:"0 0 .58 1",EASE_IN_AND_OUT:".42 0 .58 1",EASE_IN_BACK:".36 0 .66 -.56",EASE_OUT_BACK:".34 1.56 .64 1",EASE_IN_AND_OUT_BACK:".68 -.6 .32 1.6",GENTLE:".4 0 .2 1",QUICK:".2 0 0 1",BOUNCY:".34 1.56 .64 1",SLOW:".4 0 .6 1"}[t]||"0 0 .58 1"}
function sampleSpring(r={},count=36){const m=Math.max(.001,finite(r.mass,1)),k=Math.max(.001,finite(r.stiffness,100)),d=Math.max(0,finite(r.damping,10)),v=finite(r.initialVelocity,0),w0=Math.sqrt(k/m),z=d/(2*Math.sqrt(k*m)),a=[];for(let i=0;i<count;i++){const t=i/Math.max(1,count-1)*1.25;let x;if(z<1){const wd=w0*Math.sqrt(1-z*z),b=(z*w0-v)/wd;x=1-Math.exp(-z*w0*t)*(Math.cos(wd*t)+b*Math.sin(wd*t))}else x=1-Math.exp(-w0*t)*(1+(w0-v)*t);a.push(x)}a[0]=0;a[a.length-1]=1;return a}
function expand(vals,s,cfg){const values=[],times=[],splines=[];const push=(t,v)=>{t=clamp(t,0,s.totalDuration);if(times.length&&Math.abs(times[times.length-1]-t)<1e-7){values[values.length-1]=v;return}times.push(t);values.push(v)};push(0,vals[0]);s.segments.forEach((g,i)=>{const a=vals[i],b=vals[(i+1)%vals.length];push(g.transitionStart,a);if(g.easing&&g.easing.type==="CUSTOM_SPRING"&&typeof a==="number"&&typeof b==="number"){const sm=sampleSpring(g.easing.easingFunctionSpring,cfg.springSamples);sm.slice(1).forEach((p,j)=>push(g.transitionStart+(j+1)/(sm.length-1)*g.duration,lerp(a,b,p)))}else{splines.push(easingSpline(g.easing));push(g.transitionEnd,b)}});if(times[times.length-1]<s.totalDuration)push(s.totalDuration,vals[vals.length-1]);while(splines.length<times.length-1)splines.push("0 0 1 1");return{values,times,splines:numeric(values)?splines:[]}}
function animate(name,vals,s,cfg,discrete=false){if(!vals.length||allEqual(vals))return"";const e=expand(vals,s,cfg),v=e.values.map(x=>typeof x==="number"?fmt(x):String(x).replace(/&/g,"&amp;").replace(/"/g,"&quot;")).join(";"),kt=e.times.map(x=>fmt(x/s.totalDuration)).join(";"),mode=discrete?"discrete":e.splines.length?"spline":"linear",ks=e.splines.length?` keySplines="${e.splines.join(";")}"`:"";return`<animate attributeName="${name}" dur="${fmt(s.totalDuration)}s" repeatCount="indefinite" values="${v}" keyTimes="${kt}" calcMode="${mode}"${ks}/>`}
module.exports={orderStates,buildSchedule,easingSpline,sampleSpring,animate};
