figma.showUI(__html__,{width:420,height:360,themeColors:true});
const NS="svg-motion-lab",KEY="motion-id";
figma.ui.onmessage=async m=>{if(!m||m.type!=="export")return;try{figma.ui.postMessage({type:"manifest",manifest:await exportManifest(m.options||{})})}catch(e){figma.ui.postMessage({type:"error",message:e&&e.message?e.message:String(e)})}};
async function exportManifest(opt){await figma.loadAllPagesAsync();const roots=figma.currentPage.selection.filter(isState);const statesNodes=roots.length?roots:figma.currentPage.children.filter(isState);if(!statesNodes.length)throw new Error("Hãy chọn ít nhất một Frame, Component hoặc Instance state.");const nodeState=new Map(),rootIds=new Set(statesNodes.map(n=>n.id));statesNodes.forEach(r=>mapState(r,r.id,nodeState));const states=[];for(let i=0;i<statesNodes.length;i++){const root=statesNodes[i],ab=root.absoluteBoundingBox||{x:root.x||0,y:root.y||0};figma.ui.postMessage({type:"progress",message:`Đang export ${i+1}/${statesNodes.length}: ${root.name}`});const layers=[];walk(root,null,`${name(root.name)}[0]`,0,{x:ab.x||0,y:ab.y||0},layers,opt);states.push({id:root.id,name:root.name,order:i,width:n(root.width),height:n(root.height),layers,svg:opt.includeStateSvg?await exportSvg(root):null})}return{schema:"svg-motion-lab/figma-manifest@1",exportedAt:new Date().toISOString(),source:{fileName:figma.root.name,pageId:figma.currentPage.id,pageName:figma.currentPage.name},startNodeId:states[0].id,stateOrder:states.map(s=>s.id),states,transitions:transitions(states,nodeState,rootIds),calibration:{geometryPrecision:4,gradientPrecision:5,springSamples:36,layerMatchOrder:["pluginKey","semanticPath","nameTypeScore"]}}}
function isState(n){return n&&["FRAME","COMPONENT","INSTANCE","COMPONENT_SET"].includes(n.type)}
function mapState(n,id,m){m.set(n.id,id);if("children"in n)n.children.forEach(c=>mapState(c,id,m))}
function walk(node,parent,path,index,origin,out,opt){if(!opt.includeHidden&&node.visible===false)return;const pluginKey=data(node),key=pluginKey||path,ab=node.absoluteBoundingBox||{x:node.x||0,y:node.y||0,width:node.width||0,height:node.height||0};out.push({id:node.id,key,pluginKey:pluginKey||null,semanticPath:path,parentKey:parent,siblingIndex:index,name:node.name||node.type,type:node.type,visible:node.visible!==false,opacity:n("opacity"in node?node.opacity:1),blendMode:"blendMode"in node?node.blendMode:"NORMAL",bounds:{x:n(ab.x-origin.x),y:n(ab.y-origin.y),width:n(ab.width),height:n(ab.height)},size:{width:n("width"in node?node.width:ab.width),height:n("height"in node?node.height:ab.height)},rotation:n("rotation"in node?node.rotation:0),relativeTransform:mat("relativeTransform"in node?node.relativeTransform:null),fills:paints("fills"in node?node.fills:[]),strokes:paints("strokes"in node?node.strokes:[]),strokeWeight:n("strokeWeight"in node&&typeof node.strokeWeight==="number"?node.strokeWeight:0),cornerRadius:corners(node),vectorPaths:paths(node),text:text(node),reactions:clone("reactions"in node?node.reactions:[])});if("children"in node){const c=new Map();for(const child of node.children){const b=name(child.name||child.type),i=c.get(b)||0;c.set(b,i+1);walk(child,key,`${path}/${b}[${i}]`,i,origin,out,opt)}}}
function paints(v){if(!Array.isArray(v))return[];return v.filter(p=>p&&p.visible!==false).map(p=>{const r={type:p.type,visible:p.visible!==false,opacity:n(p.opacity==null?1:p.opacity),blendMode:p.blendMode||"NORMAL"};if(p.color)r.color=color(p.color,p.opacity);if(p.gradientStops)r.gradientStops=p.gradientStops.map(s=>({position:n(s.position),color:color(s.color)}));if(p.gradientHandlePositions)r.gradientHandlePositions=p.gradientHandlePositions.map(pt);if(p.imageHash)r.imageHash=p.imageHash;return r})}
function paths(node){return"vectorPaths"in node&&Array.isArray(node.vectorPaths)?node.vectorPaths.map(p=>({data:p.data,windingRule:p.windingRule})):[]}
function text(node){if(node.type!=="TEXT")return null;return{characters:node.characters,fontSize:typeof node.fontSize==="number"?n(node.fontSize):null,fontName:node.fontName&&node.fontName!==figma.mixed?clone(node.fontName):null,fontWeight:typeof node.fontWeight==="number"?node.fontWeight:null,textAlignHorizontal:node.textAlignHorizontal,textAlignVertical:node.textAlignVertical}}
function transitions(states,nodeState,rootIds){const map=new Map();for(const state of states)for(const l of state.layers)for(const r of l.reactions||[]){const actions=r.actions||(r.action?[r.action]:[]);for(const a of actions){if(!a||a.type!=="NODE"||!a.destinationId)continue;const to=rootIds.has(a.destinationId)?a.destinationId:nodeState.get(a.destinationId);if(to&&to!==state.id)map.set(`${state.id}>${to}`,{from:state.id,to,sourceLayerId:l.id,trigger:r.trigger||null,navigation:a.navigation||null,transition:a.transition||{type:"SMART_ANIMATE",duration:.3,easing:{type:"EASE_OUT"}}})}}return[...map.values()]}
async function exportSvg(node){try{return new TextDecoder("utf-8").decode(await node.exportAsync({format:"SVG",svgIdAttribute:true,svgOutlineText:false,svgSimplifyStroke:false}))}catch(e){return null}}
function corners(node){if(!("cornerRadius"in node))return null;if(typeof node.cornerRadius==="number")return{all:n(node.cornerRadius)};return{topLeft:n(node.topLeftRadius||0),topRight:n(node.topRightRadius||0),bottomRight:n(node.bottomRightRadius||0),bottomLeft:n(node.bottomLeftRadius||0)}}
function data(node){try{return node.getSharedPluginData(NS,KEY)||node.getPluginData(KEY)||""}catch(e){return""}}
function color(c,o){return{r:n(c.r),g:n(c.g),b:n(c.b),a:n(c.a==null?(o==null?1:o):c.a)}}
function pt(p){return{x:n(p.x),y:n(p.y)}}
function mat(v){return Array.isArray(v)?v.map(r=>r.map(n)):null}
function n(v){v=Number(v);return Number.isFinite(v)?Math.round(v*1e5)/1e5:0}
function name(v){return String(v||"layer").trim().toLowerCase().replace(/\s+/g,"-").replace(/[^a-z0-9_-]+/g,"").replace(/-+/g,"-")||"layer"}
function clone(v){return JSON.parse(JSON.stringify(v))}
