(function(root){
'use strict';
const previous=root.SvgMotionCompiler;
const S=root.__SMC;
if(!previous||!S)return;
const SVG_NS='http://www.w3.org/2000/svg';
const NUMERIC=['x','y','x1','y1','x2','y2','cx','cy','r','rx','ry','width','height','opacity','fill-opacity','stroke-opacity','stroke-width','stroke-dashoffset'];
const COLOR=['fill','stroke','color','stop-color','flood-color','lighting-color'];
function canonicalSegment(segment){return String(segment||'').replace(/_\d+(?=\[)/g,'')}
function canonicalId(value){const text=String(value||''),split=text.indexOf(':@root');if(split<0)return text;return text.slice(0,split)+':'+text.slice(split+1).split('/').map(canonicalSegment).join('/')}
function parseState(state){const doc=new DOMParser().parseFromString(state.svg,'image/svg+xml'),error=doc.querySelector('parsererror');if(error)throw new Error('SVG không hợp lệ ở '+(state.name||state.id)+': '+error.textContent.slice(0,160));const svg=doc.documentElement;svg.querySelectorAll('[data-motion-id]').forEach(el=>el.setAttribute('data-motion-id',canonicalId(el.getAttribute('data-motion-id'))));const map=new Map();svg.querySelectorAll('[data-motion-id]').forEach(el=>{const id=el.getAttribute('data-motion-id');if(!map.has(id))map.set(id,el)});return{state,doc,svg,map}}
function layerMap(state){const out=new Map();(state.layers||[]).forEach(layer=>out.set(canonicalId(layer.stableNodeId),layer));return out}
function numAttrs(el){const out={};NUMERIC.forEach(name=>{if(el&&el.hasAttribute(name)){const value=Number(el.getAttribute(name));if(Number.isFinite(value))out[name]=value}});return out}
function parseColor(value){const v=String(value||'').trim();let m;if(/^#[0-9a-f]{6}$/i.test(v))return[v.slice(1,3),v.slice(3,5),v.slice(5,7)].map(x=>parseInt(x,16));if((m=v.match(/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i)))return m.slice(1).map(Number);return null}
function colorAttrs(el){const out={};COLOR.forEach(name=>{if(!el||!el.hasAttribute(name))return;const parsed=parseColor(el.getAttribute(name));if(parsed)out[name]=parsed});return out}
function tokenizePath(d){return String(d||'').match(/[a-zA-Z]|-?\d*\.?\d+(?:e[-+]?\d+)?/g)||[]}
function pathTemplate(d){const tokens=tokenizePath(d),commands=tokens.filter(x=>/^[a-zA-Z]$/.test(x)),numbers=tokens.filter(x=>!/^[a-zA-Z]$/.test(x)).map(Number);return{tokens,commands:commands.join(''),numbers}}
function compatiblePaths(paths){const valid=paths.filter(Boolean);if(valid.length<2)return false;const first=pathTemplate(valid[0]);return valid.every(path=>{const next=pathTemplate(path);return next.commands===first.commands&&next.numbers.length===first.numbers.length})}
function parseTransform(value){const text=String(value||'').trim();if(!text)return[1,0,0,1,0,0];let m;if((m=text.match(/^matrix\(\s*([-+\deE.]+)[ ,]+([-+\deE.]+)[ ,]+([-+\deE.]+)[ ,]+([-+\deE.]+)[ ,]+([-+\deE.]+)[ ,]+([-+\deE.]+)\s*\)$/)))return m.slice(1).map(Number);if((m=text.match(/^translate\(\s*([-+\deE.]+)(?:[ ,]+([-+\deE.]+))?\s*\)$/)))return[1,0,0,1,Number(m[1]),Number(m[2]||0)];if((m=text.match(/^scale\(\s*([-+\deE.]+)(?:[ ,]+([-+\deE.]+))?\s*\)$/))){const x=Number(m[1]),y=Number(m[2]||m[1]);return[x,0,0,y,0,0]}return null}
function layerRotation(layer){if(!layer)return null;const b=layer.bounds||{};return{angle:Number(layer.rotation)||0,cx:(Number(b.x)||0)+(Number(b.width)||0)/2,cy:(Number(b.y)||0)+(Number(b.height)||0)/2}}
function buildTrack(id,nodes,layers){const present=nodes.map(Boolean),baseIndex=present.indexOf(true),base=nodes[baseIndex];if(!base)return null;const tags=nodes.filter(Boolean).map(n=>String(n.tagName).toLowerCase()),sameTag=tags.every(tag=>tag===tags[0]);const numeric=nodes.map(numAttrs),colors=nodes.map(colorAttrs),paths=nodes.map(n=>n&&n.getAttribute('d')||null),transforms=nodes.map(n=>n?parseTransform(n.getAttribute('transform')):null),rotations=layers.map(layerRotation);let pathMode=false;if(sameTag&&tags[0]==='path'&&compatiblePaths(paths))pathMode=true;return{id,baseIndex,tag:String(base.tagName).toLowerCase(),present,numeric,colors,paths,pathMode,transforms,rotations}}
function cloneMissingTracks(scene,tracks,states){tracks.forEach(track=>{if(track.baseIndex===0)return;const source=states[track.baseIndex].map.get(track.id);if(!source)return;const clone=source.cloneNode(true);clone.setAttribute('data-motion-id',track.id);clone.setAttribute('opacity','0');scene.appendChild(clone)})}
function runtime(data){const json=JSON.stringify(data).replace(/</g,'\\u003c');return"(()=>{const D="+json+",svg=document.currentScript.ownerDocument.documentElement,scene=svg.querySelector('#motion-scene');let start=performance.now(),manual=false,paused=false;const C=v=>Math.max(0,Math.min(1,v)),L=(a,b,p)=>(Number(a)||0)+((Number(b)||0)-(Number(a)||0))*p,E=p=>p*p*(3-2*p),pick=(arr,i)=>arr[i]!=null?arr[i]:arr.slice(0,i).reverse().find(v=>v!=null)??arr.find(v=>v!=null);function state(t){let active=0,segment=null;for(const s of D.segments){if(t<s.start){active=s.from;break}active=s.to;if(t>=s.start&&t<s.end){segment=s;break}}return{active,segment}}function color(a,b,p){return'rgb('+[0,1,2].map(i=>Math.round(L(a[i],b[i],p))).join(',')+')'}function path(track,from,to,p){const a=pick(track.paths,from),b=pick(track.paths,to);if(!a||!b)return null;const ta=a.match(/[a-zA-Z]|-?\\d*\\.?\\d+(?:e[-+]?\\d+)?/g)||[],tb=b.match(/[a-zA-Z]|-?\\d*\\.?\\d+(?:e[-+]?\\d+)?/g)||[];let ni=0;return ta.map((token,index)=>/^[a-zA-Z]$/.test(token)?token:String(L(Number(token),Number(tb[index]),p))).join(' ')}function render(t){const total=Math.max(.001,D.duration);t=D.infinite?((t%total)+total)%total:C(t/total)*total;const q=state(t),p=q.segment?E(C((t-q.segment.start)/Math.max(.001,q.segment.end-q.segment.start))):0,from=q.segment?q.segment.from:q.active,to=q.segment?q.segment.to:q.active;for(const tr of D.tracks){const el=scene.querySelector('[data-motion-id=\"'+CSS.escape(tr.id)+'\"]');if(!el)continue;const pa=tr.present[from],pb=tr.present[to];if(!pa&&!pb){el.setAttribute('visibility','hidden');continue}el.setAttribute('visibility','visible');const na=pick(tr.numeric,from)||{},nb=pick(tr.numeric,to)||{};for(const name of D.numeric){if(na[name]!=null||nb[name]!=null)el.setAttribute(name,String(L(na[name],nb[name],p)))}const ca=pick(tr.colors,from)||{},cb=pick(tr.colors,to)||{};for(const name of D.colors){if(ca[name]&&cb[name])el.setAttribute(name,color(ca[name],cb[name],p))}if(tr.pathMode){const d=path(tr,from,to,p);if(d)el.setAttribute('d',d)}const ma=pick(tr.transforms,from),mb=pick(tr.transforms,to);if(ma&&mb)el.setAttribute('transform','matrix('+ma.map((v,i)=>L(v,mb[i],p)).join(' ')+')');const ra=pick(tr.rotations,from),rb=pick(tr.rotations,to);if(ra&&rb){let a=ra.angle,b=rb.angle;while(b-a>180)b-=360;while(a-b>180)b+=360;el.setAttribute('transform','rotate('+L(a,b,p)+' '+L(ra.cx,rb.cx,p)+' '+L(ra.cy,rb.cy,p)+')')}if(pa&&!pb)el.setAttribute('opacity',String(1-p));else if(!pa&&pb)el.setAttribute('opacity',String(p))}}}function tick(now){if(!manual&&!paused)render((now-start)/1000);requestAnimationFrame(tick)}svg.__motionController={seek(t){manual=true;render(Number(t)||0)},play(){manual=false;paused=false;start=performance.now()},pause(){paused=true},restart(){manual=false;paused=false;start=performance.now();render(0)}};render(0);requestAnimationFrame(tick)})()"}
function validate(manifest){if(!manifest||manifest.schema!=='svg-motion-lab/figma-manifest@4')throw new Error('Multi-track engine yêu cầu manifest @4.');if(Number(manifest.fidelityMetadataVersion||0)<4||!manifest.capabilities||!manifest.capabilities.embeddedMotionIds)throw new Error('Hãy export lại bằng plugin mới để có embedded motion IDs.');if(!Array.isArray(manifest.states)||manifest.states.length<2)throw new Error('Manifest cần ít nhất 2 states.');return true}
function compile(manifest,options){validate(manifest);options=options||{};const base=options.baseSchedule||S.buildBaseSchedule(manifest),schedule=S.customSchedule(base,options.customSegments,options.infinite);const ordered=schedule.stateIds.map(id=>manifest.states.find(state=>state.id===id)).filter(Boolean),states=ordered.map(parseState),layerMaps=ordered.map(layerMap),ids=new Set();states.forEach(state=>state.map.forEach((_,id)=>ids.add(id)));const tracks=[...ids].map(id=>buildTrack(id,states.map(state=>state.map.get(id)||null),layerMaps.map(map=>map.get(id)||null))).filter(Boolean);const baseSvg=states[0].svg.cloneNode(true);baseSvg.querySelectorAll('script').forEach(script=>script.remove());baseSvg.id='motion-svg';baseSvg.setAttribute('data-render-mode','multi-track-smart-animate');baseSvg.setAttribute('data-duration',S.round(schedule.totalDuration));baseSvg.setAttribute('data-infinite',String(schedule.infinite));let scene=baseSvg.querySelector('#motion-scene');if(!scene){scene=document.createElementNS(SVG_NS,'g');scene.id='motion-scene';[...baseSvg.children].filter(child=>String(child.tagName).toLowerCase()!=='defs').forEach(child=>scene.appendChild(child));baseSvg.appendChild(scene)}cloneMissingTracks(scene,tracks,states);const data={duration:schedule.totalDuration,infinite:schedule.infinite,numeric:NUMERIC,colors:COLOR,segments:schedule.segments.map(segment=>({from:schedule.stateIds.indexOf(segment.from),to:schedule.stateIds.indexOf(segment.to),start:segment.transitionStart,end:segment.transitionEnd})),tracks};const script=document.createElementNS(SVG_NS,'script');script.textContent=runtime(data);baseSvg.appendChild(script);const report={renderMode:'multi-track-smart-animate',totalTracks:tracks.length,pathMorphTracks:tracks.filter(t=>t.pathMode).length,transformTracks:tracks.filter(t=>t.transforms.filter(Boolean).length>1).length,rotationTracks:tracks.filter(t=>t.rotations.filter(Boolean).length>1).length,colorTracks:tracks.filter(t=>t.colors.some(c=>Object.keys(c).length)).length,presenceTracks:tracks.filter(t=>t.present.some(Boolean)&&t.present.some(v=>!v)).length,fullStateSnapshots:0,embeddedMotionIds:true,genericAnimationTypes:['numeric-geometry','translate','scale','matrix-transform','rotation','opacity','visibility','solid-color','path-morph','appear-disappear']};const svg='<?xml version="1.0" encoding="UTF-8"?>'+new XMLSerializer().serializeToString(baseSvg),html=S.buildHtml(svg,schedule),ir={version:5,startStateId:schedule.stateIds[0],stateOrder:schedule.stateIds.slice(),playback:{infinite:schedule.infinite,totalDuration:schedule.totalDuration,segments:schedule.segments},smartAnimate:report};return{svg,html,ir,report:{report:Object.assign({manifestSchema:manifest.schema,prototypeReady:true,snapshotsReady:true,infinite:schedule.infinite,customDuration:schedule.totalDuration},report),schedule},schedule,semanticReport:report}}
root.SvgMotionCompiler={validate,buildBaseSchedule:S.buildBaseSchedule,compile};
})(window);
